### PR TITLE
deleted unnessesary constructor

### PR DESCRIPTION
**Pull request by piotrcurious**
constructor should be placed in final project, not in the library, otherwise it prevents multiple instances being possible.

### CODE REVIEW

**Comment by kcl93** [comment]
Hi @piotrcurious 
The line you deleted is only the default instance of the VT100_Control but not the constructor. Having a default instance should make it possible to use the VT100 library similar to the "Serial" library.
The constructor itself ist public and nothing should prevent you from creating any instances (beside one called "VT100" since that is the default one) in your project.
Kind regards,
kcl93
In which cases do you get errors when try to create more to instances of this library?

**Comment by piotrcurious** [comment]
Hello,
I deleted default instance because it is not wise to pass it anywhere, it is up to user to define instances, otherwise it might clash with other libraries, f.e. if one uses vt100 emulator with tv or vga out itself on arduino due, stm32 or esp32 (so not sending data over serial but over loopback to vt100 terminal running on controller itself)
Also when creating more instances with different naming, the default one is still dangling. optimising compiler will remove it, but it's just wrong.

Serial library is one of core arduino libraries though it is also disputable if it really should be created by default. Lets not copy errors :)

Greetings
-------- Original Message --------

**Comment by kcl93** [comment]
Makes sense... In this case it would be nice if you could also remove the default instance from VT100.h and check that the examples are still working.

**Review by kcl93 — APPROVED** [review]

**Comment by kcl93** [comment]
Thanks @piotrcurious for those commits!

**Pull request merged**
